### ISSUE TITLE
Unhandled Exception When Calling GetResources for football

### ISSUE THREAD

**Issue by chipwillman** [sportingsolutions/SS.Integration.UnifiedDataAPIClient.DotNet#53]
When requesting the resources for "foorball" feature, the service is returning an internal server error.

2015-02-09 02:12:12,526 [179] ERROR SportingSolutions.Udapi.Sdk.Feature - GetResources Http Error
Uri=http://apicui.sportingsolutions.com/UnifiedDataAPI/Football/YFUBu4lobCJeX1v-yFZMyab5REU3
Request.Method=GET
Request.TimeOut=60000
ResponseStatus=None
StatusCode=InternalServerError ()
Content={"Message":"An error has occurred."}
Exception=Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[SportingSolutions.Udapi.Sdk.Model.RestItem]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Message', line 1, position 11.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at SportingSolutions.Udapi.Sdk.Extensions.JsonHelper.FromJson[T](String json, Boolean expectIsoDate)
   at SportingSolutions.Udapi.Sdk.Clients.ConnectClient.Request[T](Uri uri, Method method, Object body, String contentType, Int32 timeout)

**Comment by pzanetti** [comment]
hello @chipwillman 

Apologies for the late reply - that is an expected error that you should manage on your code. It is often caused by network glitches. The error itself means that the sdk was not able to deserialize the received data - most likely because the sdk received a corrupted data or no data at all.

In this situation, I would suggest you to wrap the call to GetResources in a try-catch statement and retry the request in case of exceptions.

Thanks
Piero
